### ISSUE TITLE
Beiträge jährlich (und im Voraus), aber Mitgliedschaft erlischt nach 5 Monate ausstehend

### ISSUE THREAD

**Issue by cluck** [ccc-ch/statuten#2]
Diese Regeln harmonieren gemäss Nyquist-Shannon sampling theorem nicht so gut zusammen.

Und da sie im Voraus zu zahlen sind, ist auch gar nicht klar was mit säumigen Mitglieder ist: sind sie überhaupt erst Mitglieder geworden?

Gefunden beim Übersetzen auf Italienisch.

**Comment by KampfCaspar** [comment]
Mitgliedschaft und Beiträge sind zwei unterschiedliche Dinge.

Mit einem Aufnahmebeschluss wird die Mitgliedschaft begründet - dazu braucht es noch gar keine Zahlung.

Wenn ein Mitglied später nicht zahlt, zählt der Zahlungsverzug als Austrittserklärung. Die Mitgliedschaft erlischt nicht rückwirkend.

Ich sehe keinen Handlungsbedarf

**Comment by KampfCaspar** [comment]
#10
